2.0: MESH Hydrology parameters input file (Version 2.0)
##### Option Flags #####
----#
    0                                                       # Number of option flags
##### Channel routing parameters per river class #####
-------#
4                                                           # Number of channel routing parameters
R2N    0.300    0.400    0.400    0.400    0.400            # comment for line
R1N    0.020    0.020    0.020    0.020    0.020            # comment for line
PWR    2.370    2.370    2.370    2.370    2.370            # comment for line
FLZ    0.001    0.001    0.001    0.001    0.001            # comment for line
##### GRU class independent hydrologic parameters #####     # 10comment line 13                                                           | *
-------#                                                    # 11comment line 14                                                           | *
       0                                                    # Number of GRU independent hydrologic parameters
##### GRU class dependent hydrologic parameters #####       # 18comment line 16                                                           | *
-------#                                                    # 19comment line 17                                                           | *
       4                                                    # 21Number of GRU dependent hydrologic parameters                             | I8
!     10      20      30      40      50      60      70      80      90      100      
ZSNL  0.050   0.050   0.050   0.050   0.050   0.050   0.050   0.050   0.050   0.050
ZPLS  0.060   0.060   0.060   0.060   0.060   0.060   0.060   0.060   0.060   0.060
ZPLG  0.200   0.200   0.200   0.200   0.200   0.200   0.200   0.200   0.200   0.200
IWF   1       1       1       1       1       1       1       1       1       1
